---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by da.
--- DateTime: 2021/2/16 20:41
---

-- 声明变量
local methodKey = KEYS[1]

-- redis控制台打印日志
redis.log(redis.LOG_INFO, "key is ", methodKey)

-- 传入的限流值
local limit = tonumber(ARGV[1])

-- 获取当前限流个数 可能为nil（key不存在）
local count = tonumber(redis.call('get', methodKey) or '0')

if count + 1 > limit then
    -- 超出限流数  拒绝
    redis.log(redis.LOG_INFO, "limit result is ", false)
    return false
end

-- 自增1
redis.call('INCRBY',methodKey,1)
-- 设置过期时间 一秒
redis.call('EXPIRE',methodKey,1)

return true

