spring:
  shardingsphere:
    datasource:
      names: db0,db1
      db0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.139.101:3306/test
        username: da
        password: dashan007@
      db1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.139.103:3306/test
        username: da
        password: dashan007@
    sharding:
      tables:
        t_order:
          actual-data-nodes: db$->{0..1}.t_order_$->{1..2}
          database-strategy:
            inline:
              sharding-column: spu_id
              algorithm-expression: db$->{spu_id % 2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: t_order_$->{id % 2}

#          key-generator:
#            column: order_id
#            type: SNOWFLAKE
#      default-database-strategy:
#        inline:
#          sharding-column: spu_id
#          algorithm-expression: db$->{spu_id % 2}
mybatis:
  mapper-locations: classpath:/mappers/*.xml
logging:
  pattern:
    dateformat: HH:mm:ss