spring:
  activiti:
    history-level: full
    # 自动部署验证设置:
    # true（默认）自动部署流程
    # false 不自动部署，需要手动部署发布流程
    check-process-definitions: false
      # 可选值为: false,true,create-drop,drop-create
      # 默认为true。为true表示activiti会对数据库中的表进行更新操作，如果不存在，则进行创建。
    database-schema-update: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dashan

server:
  port: 3333